### ISSUE TITLE
ActionController::RoutingError (No route matches [GET] "/assets/link-external.svg")

### ISSUE THREAD

**Issue by garethrees** [mysociety/foi-for-councils#147]
Seeing quite a few of these in the production log. Not sure what's calling it.

```
I, [2018-06-26T01:03:29.223160 #28505]  INFO -- : [b0e8f77a-4477-41db-a9dd-ed004e1f544a] Started GET "/assets/link-external.svg" for 46.235.226.171 at 2018-06-26 01:03:29 +0100
F, [2018-06-26T01:03:29.225182 #28505] FATAL -- : [b0e8f77a-4477-41db-a9dd-ed004e1f544a]
F, [2018-06-26T01:03:29.225303 #28505] FATAL -- : [b0e8f77a-4477-41db-a9dd-ed004e1f544a] ActionController::RoutingError (No route matches [GET] "/assets/link-external.svg"):
F, [2018-06-26T01:03:29.225394 #28505] FATAL -- : [b0e8f77a-4477-41db-a9dd-ed004e1f544a]
F, [2018-06-26T01:03:29.225479 #28505] FATAL -- : [b0e8f77a-4477-41db-a9dd-ed004e1f544a] /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
[b0e8f77a-4477-41db-a9dd-ed004e1f544a] /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[b0e8f77a-4477-41db-a9dd-ed004e1f544a] /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/rack/logger.rb:38:in `call_app'
[b0e8f77a-4477-41db-a9dd-ed004e1f544a] /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/rack/logger.rb:26:in `block in call'
[b0e8f77a-4477-41db-a9dd-ed004e1f544a] /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:71:in `block in tagged'
[b0e8f77a-4477-41db-a9dd-ed004e1f544a] /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:28:in `tagged'
[b0e8f77a-4477-41db-a9dd-ed004e1f544a] /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:71:in `tagged'
[b0e8f77a-4477-41db-a9dd-ed004e1f544a] /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/rack/logger.rb:26:in `call'
[b0e8f77a-4477-41db-a9dd-ed004e1f544a] /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[b0e8f77a-4477-41db-a9dd-ed004e1f544a] /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/request_id.rb:27:in `call'
[b0e8f77a-4477-41db-a9dd-ed004e1f544a] /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'
[b0e8f77a-4477-41db-a9dd-ed004e1f544a] /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/runtime.rb:22:in `call'
[b0e8f77a-4477-41db-a9dd-ed004e1f544a] /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[b0e8f77a-4477-41db-a9dd-ed004e1f544a] /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/executor.rb:14:in `call'
[b0e8f77a-4477-41db-a9dd-ed004e1f544a] /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/sendfile.rb:111:in `call'
[b0e8f77a-4477-41db-a9dd-ed004e1f544a] /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:524:in `call'
[b0e8f77a-4477-41db-a9dd-ed004e1f544a] /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
[b0e8f77a-4477-41db-a9dd-ed004e1f544a] /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
[b0e8f77a-4477-41db-a9dd-ed004e1f544a] /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
[b0e8f77a-4477-41db-a9dd-ed004e1f544a] /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
[b0e8f77a-4477-41db-a9dd-ed004e1f544a] /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by garethrees** [comment]
Maybe the 404 page or something and we're trying to call an asset by name, but rails doesn't generate non-digest assets any more?
