### ISSUE TITLE
[ERROR] curated_links#new (ActionView::Template::Error) "undefined method `gsub' for nil:NilClass"

### ISSUE THREAD

**Issue by garethrees** [mysociety/foi-for-councils#163]
```
An ActionView::Template::Error occurred in curated_links#new:

undefined method `gsub' for nil:NilClass
app/helpers/suggestions_helper.rb:8:in `format_summary'


-------------------------------
Request:
-------------------------------

* URL : https://foi.hackney.gov.uk/admin/curated_links/new
* HTTP Method: GET
* Parameters : {"controller"=>"admin/curated_links", "action"=>"new"}
* Timestamp : 2018-07-31 12:47:20 UTC

-------------------------------
Backtrace:
-------------------------------

app/helpers/suggestions_helper.rb:8:in `format_summary'
app/views/foi/suggestions/_suggestion.html.erb:7:in `block in _app_views_foi_suggestions__suggestion_html_erb___2846324494789854640_47147610037580'
app/views/foi/suggestions/_suggestion.html.erb:1:in `_app_views_foi_suggestions__suggestion_html_erb___2846324494789854640_47147610037580'
app/views/admin/curated_links/_preview.html.erb:3:in `_app_views_admin_curated_links__preview_html_erb___1795969079557161942_47147610163080'
app/views/admin/curated_links/new.html.erb:16:in `_app_views_admin_curated_links_new_html_erb__1200504514149776310_47147610982040'
```

**Comment by garethrees** [comment]
This got fixed after deploying https://github.com/mysociety/foi-for-councils/pull/158.
