### ISSUE TITLE
[ERROR] (Infreemation::ResponseError) "JSON invalid (You do not have permission to view this directory or page."

### ISSUE THREAD

**Issue by garethrees** [mysociety/foi-for-councils#319]
```
An Infreemation::ResponseError occurred in background at 2020-07-10 01:00:00 UTC :

JSON invalid (You do not have permission to view this directory or page.)
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/infreemation-0.2.1/lib/infreemation/api.rb:50:in `rescue in block in parser'

-------------------------------
Backtrace:
-------------------------------

/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/infreemation-0.2.1/lib/infreemation/api.rb:50:in `rescue in block in parser'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/infreemation-0.2.1/lib/infreemation/api.rb:45:in `block in parser'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:807:in `process_result'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:725:in `block in transmit'
/opt/rbenv/versions/2.5.8/lib/ruby/2.5.0/net/http.rb:910:in `start'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/resource.rb:67:in `post'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/infreemation-0.2.1/lib/infreemation/api.rb:17:in `get'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/infreemation-0.2.1/lib/infreemation/request.rb:19:in `where'
/data/vhost/hackney-foi.mysociety.org/foi-for-councils-2020-06-16T09-14-31/app/services/disclosure_log.rb:24:in `import'
/data/vhost/hackney-foi.mysociety.org/foi-for-councils-2020-06-16T09-14-31/app/services/disclosure_log.rb:18:in `import!'
/data/vhost/hackney-foi.mysociety.org/foi-for-councils-2020-06-16T09-14-31/app/workers/import_disclosure_log_worker.rb:11:in `perform'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:187:in `execute_job'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:169:in `block (2 levels) in process'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:168:in `block in process'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:139:in `block (6 levels) in dispatch'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:98:in `local'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:138:in `block (5 levels) in dispatch'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:42:in `block in call'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/execution_wrapper.rb:87:in `wrap'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/reloader.rb:73:in `block in wrap'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/execution_wrapper.rb:87:in `wrap'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/reloader.rb:72:in `wrap'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:41:in `call'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:134:in `block (4 levels) in dispatch'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:199:in `stats'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:129:in `block (3 levels) in dispatch'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_logger.rb:8:in `call'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:128:in `block (2 levels) in dispatch'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:73:in `global'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:127:in `block in dispatch'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:48:in `with_context'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:126:in `dispatch'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:167:in `process'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:85:in `process_one'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:73:in `run'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:16:in `watchdog'
/data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'

-------------------------------
Data:
-------------------------------

* data: {:sidekiq=>
{:context=>"Job raised exception",
:job=>
{"class"=>"ImportDisclosureLogWorker",
"args"=>["week"],
"queue"=>"default",
"retry"=>true,
"jid"=>"6e8ee0cdfdad076ccb2ae694",
"created_at"=>1594342800.1203146,
"enqueued_at"=>1594342800.1203754},
:jobstr=>
"{\"class\":\"ImportDisclosureLogWorker\",\"args\":[\"week\"],\"queue\":\"default\",\"retry\":true,\"jid\":\"6e8ee0cdfdad076ccb2ae694\",\"created_at\":1594342800.1203146,\"enqueued_at\":1594342800.1203754}"}}
```

**Comment by garethrees** [comment]
Emailed Infreemation https://groups.google.com/u/1/a/mysociety.org/g/clientsupport-council-foi/c/ZPeTrLhXQGI

**Comment by garethrees** [comment]
Caused by a firewall change on their end. Submissions going through successfully today.
