### ISSUE TITLE
 [ERROR] (JSON::GeneratorError) "source sequence is illegal/malformed utf-8"

### ISSUE THREAD

**Issue by garethrees** [mysociety/foi-for-councils#326]
```
A JSON::GeneratorError occurred in background at 2020-08-19 04:52:23 UTC :

source sequence is illegal/malformed utf-8
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/core_ext/object/json.rb:38:in `to_json'

-------------------------------
Backtrace:
-------------------------------

/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/core_ext/object/json.rb:38:in `to_json'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/core_ext/object/json.rb:38:in `to_json'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/json/encoding.rb:57:in `to_json'
/opt/rbenv/versions/2.5.8/lib/ruby/2.5.0/json/common.rb:224:in `generate'
/opt/rbenv/versions/2.5.8/lib/ruby/2.5.0/json/common.rb:224:in `generate'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/json/encoding.rb:102:in `stringify'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/json/encoding.rb:35:in `encode'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/json/encoding.rb:22:in `encode'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/type/json.rb:18:in `serialize'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.4.2/lib/active_model/type/helpers/mutable.rb:8:in `cast'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.4.2/lib/active_model/attribute.rb:175:in `type_cast'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.4.2/lib/active_model/attribute.rb:42:in `value'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.4.2/lib/active_model/attribute_set.rb:48:in `fetch_value'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/attribute_methods/read.rb:77:in `_read_attribute'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/attribute_methods/read.rb:40:in `__temp__071697c6f61646'
/data/vhost/hackney-foi.staging.mysociety.org/foi-for-councils-2020-04-01T13-25-14/app/models/published_request.rb:19:in `save_or_destroy!'
/data/vhost/hackney-foi.staging.mysociety.org/foi-for-councils-2020-04-01T13-25-14/app/models/published_request.rb:14:in `create_update_or_destroy_from_api!'
/data/vhost/hackney-foi.staging.mysociety.org/foi-for-councils-2020-04-01T13-25-14/app/services/disclosure_log.rb:25:in `block in import'
/data/vhost/hackney-foi.staging.mysociety.org/foi-for-councils-2020-04-01T13-25-14/app/services/disclosure_log.rb:24:in `map'
/data/vhost/hackney-foi.staging.mysociety.org/foi-for-councils-2020-04-01T13-25-14/app/services/disclosure_log.rb:24:in `import'
/data/vhost/hackney-foi.staging.mysociety.org/foi-for-councils-2020-04-01T13-25-14/app/services/disclosure_log.rb:18:in `import!'
/data/vhost/hackney-foi.staging.mysociety.org/foi-for-councils-2020-04-01T13-25-14/app/workers/import_disclosure_log_worker.rb:11:in `perform'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:187:in `execute_job'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:169:in `block (2 levels) in process'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:168:in `block in process'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:139:in `block (6 levels) in dispatch'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:98:in `local'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:138:in `block (5 levels) in dispatch'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:42:in `block in call'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/execution_wrapper.rb:87:in `wrap'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/reloader.rb:73:in `block in wrap'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/execution_wrapper.rb:87:in `wrap'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/reloader.rb:72:in `wrap'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:41:in `call'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:134:in `block (4 levels) in dispatch'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:199:in `stats'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:129:in `block (3 levels) in dispatch'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_logger.rb:8:in `call'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:128:in `block (2 levels) in dispatch'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:73:in `global'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:127:in `block in dispatch'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:48:in `with_context'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:126:in `dispatch'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:167:in `process'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:85:in `process_one'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:73:in `run'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:16:in `watchdog'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'

-------------------------------
Data:
-------------------------------

* data: {:sidekiq=>
{:context=>"Job raised exception",
:job=>
{"class"=>"ImportDisclosureLogWorker",
"args"=>["all"],
"queue"=>"default",
"retry"=>true,
"jid"=>"347a8a53cb1931074922d7f8",
"created_at"=>1561946400.211675,
"enqueued_at"=>1597812738.1028073,
"error_message"=>"source sequence is illegal/malformed utf-8",
"error_class"=>"JSON::GeneratorError",
"failed_at"=>1561946401.78338,
"retry_count"=>21,
"retried_at"=>1585747559.2393963},
:jobstr=>
"{\"class\":\"ImportDisclosureLogWorker\",\"args\":[\"all\"],\"queue\":\"default\",\"retry\":true,\"jid\":\"347a8a53cb1931074922d7f8\",\"created_at\":1561946400.211675,\"enqueued_at\":1597812738.1028073,\"error_message\":\"source sequence is illegal/malformed utf-8\",\"error_class\":\"JSON::GeneratorError\",\"failed_at\":1561946401.78338,\"retry_count\":21,\"retried_at\":1585747559.2393963}"}}
```

**Comment by garethrees** [comment]
Had another one of these

```

-------------------------------
Data:
-------------------------------

* data: {:sidekiq=>
{:context=>"Job raised exception",
:job=>
{"class"=>"ImportDisclosureLogWorker",
"args"=>["all"],
"queue"=>"default",
"retry"=>true,
"jid"=>"347a8a53cb1931074922d7f8",
"created_at"=>1561946400.211675,
"enqueued_at"=>1598047338.008469,
"error_message"=>"source sequence is illegal/malformed utf-8",
"error_class"=>"JSON::GeneratorError",
"failed_at"=>1561946401.78338,
"retry_count"=>22,
"retried_at"=>1597812743.752312},
:jobstr=>
"{\"class\":\"ImportDisclosureLogWorker\",\"args\":[\"all\"],\"queue\":\"default\",\"retry\":true,\"jid\":\"347a8a53cb1931074922d7f8\",\"created_at\":1561946400.211675,\"enqueued_at\":1598047338.008469,\"error_message\":\"source sequence is illegal/malformed utf-8\",\"error_class\":\"JSON::GeneratorError\",\"failed_at\":1561946401.78338,\"retry_count\":22,\"retried_at\":1597812743.752312}"}}
```
