### ISSUE TITLE
[ERROR] (Infreemation::ResponseError) "JSON invalid (<head><title>Object moved</title>"

### ISSUE THREAD

**Issue by garethrees** [mysociety/foi-for-councils#332]
```
An Infreemation::ResponseError occurred in background at 2020-09-11 01:00:54 UTC :

  JSON invalid (<head><title>Object moved</title></head>
<body><h1>Object Moved</h1>This object may be found <a HREF)
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/infreemation-0.2.2/lib/infreemation/api.rb:50:in `rescue in block in parser'

  -------------------------------
Backtrace:
-------------------------------

  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/infreemation-0.2.2/lib/infreemation/api.rb:50:in `rescue in block in parser'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/infreemation-0.2.2/lib/infreemation/api.rb:45:in `block in parser'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:807:in `process_result'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:725:in `block in transmit'
  /opt/rbenv/versions/2.5.8/lib/ruby/2.5.0/net/http.rb:910:in `start'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/resource.rb:67:in `post'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/infreemation-0.2.2/lib/infreemation/api.rb:17:in `get'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/infreemation-0.2.2/lib/infreemation/request.rb:19:in `where'
  /data/vhost/hackney-foi.mysociety.org/foi-for-councils-2020-08-07T08-36-22/app/services/disclosure_log.rb:24:in `import'
  /data/vhost/hackney-foi.mysociety.org/foi-for-councils-2020-08-07T08-36-22/app/services/disclosure_log.rb:18:in `import!'
  /data/vhost/hackney-foi.mysociety.org/foi-for-councils-2020-08-07T08-36-22/app/workers/import_disclosure_log_worker.rb:11:in `perform'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:187:in `execute_job'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:169:in `block (2 levels) in process'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:133:in `invoke'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:168:in `block in process'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:139:in `block (6 levels) in dispatch'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:98:in `local'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:138:in `block (5 levels) in dispatch'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:42:in `block in call'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/execution_wrapper.rb:87:in `wrap'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/reloader.rb:73:in `block in wrap'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/execution_wrapper.rb:87:in `wrap'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/reloader.rb:72:in `wrap'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:41:in `call'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:134:in `block (4 levels) in dispatch'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:199:in `stats'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:129:in `block (3 levels) in dispatch'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_logger.rb:8:in `call'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:128:in `block (2 levels) in dispatch'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:73:in `global'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:127:in `block in dispatch'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:48:in `with_context'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:126:in `dispatch'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:167:in `process'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:85:in `process_one'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:73:in `run'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:16:in `watchdog'
  /data/vhost/hackney-foi.mysociety.org/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'

-------------------------------
Data:
-------------------------------

  * data: {:sidekiq=>
    {:context=>"Job raised exception",
     :job=>
      {"class"=>"ImportDisclosureLogWorker",
       "args"=>["week"],
       "queue"=>"default",
       "retry"=>true,
       "jid"=>"21aa4e20319b14d6aa7b8f57",
       "created_at"=>1599786000.0852954,
       "enqueued_at"=>1599786042.2581663,
       "error_message"=>
        "JSON invalid (<head><title>Object moved</title></head>\n" +
        "<body><h1>Object Moved</h1>This object may be found <a HREF)",
       "error_class"=>"Infreemation::ResponseError",
       "failed_at"=>1599786015.7592835,
       "retry_count"=>0},
     :jobstr=>
      "{\"class\":\"ImportDisclosureLogWorker\",\"args\":[\"week\"],\"queue\":\"default\",\"retry\":true,\"jid\":\"21aa4e20319b14d6aa7b8f57\",\"created_at\":1599786000.0852954,\"enqueued_at\":1599786042.2581663,\"error_message\":\"JSON invalid (<head><title>Object moved</title></head>\\n<body><h1>Object Moved</h1>This object may be found <a HREF)\",\"error_class\":\"Infreemation::ResponseError\",\"failed_at\":1599786015.7592835,\"retry_count\":0}"}}
```

**Comment by gbp** [comment]
Not clear why this is occuring, running via in the console works:

```
irb(main):002:0> Infreemation::Request.where rt: 'published', startdate: (Time.zone.today - 1.week), enddate: Time.zone.today
GET /foi/ with {:rt=>"published", :startdate=>Mon, 07 Sep 2020, :enddate=>Mon, 14 Sep 2020}

    { "status": "OK", "ref": "0", "error": "No data is available" }

=> []
```

Possible overnight maintainence?

**Comment by garethrees** [comment]
> Possible overnight maintainence?

Guess so. Will reopen if we see more.
