### ISSUE TITLE
[ERROR] (Infreemation::ResponseError) "JSON invalid (<head><title>Object moved</title>…

### ISSUE THREAD

**Issue by garethrees** [mysociety/foi-for-councils#364]
```
An Infreemation::ResponseError occurred in background at 2021-02-11 17:54:56 UTC :

JSON invalid (<head><title>Object moved</title></head>
<body><h1>Object Moved</h1>This object may be found <a HREF)
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/infreemation-0.2.2/lib/infreemation/api.rb:50:in `rescue in block in parser'

-------------------------------
Backtrace:
-------------------------------

/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/infreemation-0.2.2/lib/infreemation/api.rb:50:in `rescue in block in parser'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/infreemation-0.2.2/lib/infreemation/api.rb:45:in `block in parser'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:807:in `process_result'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:725:in `block in transmit'
/opt/rbenv/versions/2.5.8/lib/ruby/2.5.0/net/http.rb:910:in `start'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/resource.rb:67:in `post'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/infreemation-0.2.2/lib/infreemation/api.rb:24:in `post'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/infreemation-0.2.2/lib/infreemation/request.rb:32:in `save!'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/infreemation-0.2.2/lib/infreemation/request.rb:28:in `initialize'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/infreemation-0.2.2/lib/infreemation/request.rb:14:in `new'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/infreemation-0.2.2/lib/infreemation/request.rb:14:in `create!'
/APP_ROOT/foi-for-councils-2020-10-01T15-35-58/app/services/deliver_submission.rb:11:in `call'
/APP_ROOT/foi-for-councils-2020-10-01T15-35-58/app/models/submission.rb:44:in `deliver!'
/APP_ROOT/foi-for-councils-2020-10-01T15-35-58/app/models/submission.rb:40:in `deliver'
/APP_ROOT/foi-for-councils-2020-10-01T15-35-58/app/workers/deliver_submission_worker.rb:13:in `block in perform'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/locking/pessimistic.rb:84:in `block in with_lock'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/opt/rbenv/versions/2.5.8/lib/ruby/2.5.0/monitor.rb:235:in `mon_synchronize'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/transactions.rb:212:in `transaction'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/transactions.rb:301:in `transaction'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.3/lib/active_record/locking/pessimistic.rb:82:in `with_lock'
/APP_ROOT/foi-for-councils-2020-10-01T15-35-58/app/workers/deliver_submission_worker.rb:13:in `perform'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:187:in `execute_job'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:169:in `block (2 levels) in process'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:168:in `block in process'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:139:in `block (6 levels) in dispatch'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:98:in `local'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:138:in `block (5 levels) in dispatch'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:42:in `block in call'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/execution_wrapper.rb:87:in `wrap'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/reloader.rb:73:in `block in wrap'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/execution_wrapper.rb:87:in `wrap'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/reloader.rb:72:in `wrap'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:41:in `call'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:134:in `block (4 levels) in dispatch'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:199:in `stats'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:129:in `block (3 levels) in dispatch'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_logger.rb:8:in `call'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:128:in `block (2 levels) in dispatch'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:73:in `global'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:127:in `block in dispatch'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:48:in `with_context'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:126:in `dispatch'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:167:in `process'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:85:in `process_one'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:73:in `run'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:16:in `watchdog'
/APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'

-------------------------------
Data:
-------------------------------

* data: {:sidekiq=>
{:context=>"Job raised exception",
:job=>
{"class"=>"DeliverSubmissionWorker",
"args"=>[2130],
"retry"=>true,
"queue"=>"default",
"jid"=>"87b4d7bfb441964a6e8ac3f8",
"created_at"=>1613065705.016786,
"enqueued_at"=>1613066095.8173413,
"error_message"=>
"JSON invalid (<head><title>Object moved</title></head>\n" +
"<body><h1>Object Moved</h1>This object may be found <a HREF)",
"error_class"=>"Infreemation::ResponseError",
"failed_at"=>1613065705.5539634,
"retry_count"=>3,
"retried_at"=>1613065946.6529295},
:jobstr=>
"{\"class\":\"DeliverSubmissionWorker\",\"args\":[2130],\"retry\":true,\"queue\":\"default\",\"jid\":\"87b4d7bfb441964a6e8ac3f8\",\"created_at\":1613065705.016786,\"enqueued_at\":1613066095.8173413,\"error_message\":\"JSON invalid (<head><title>Object moved</title></head>\\n<body><h1>Object Moved</h1>This object may be found <a HREF)\",\"error_class\":\"Infreemation::ResponseError
```

**Comment by garethrees** [comment]
Couple of `DeliverSubmissionWorker` failures last week. Need to check that this was temporary and that the requests have been delivered.

**Comment by gbp** [comment]
Just confirmed that these have been delivered
