### ISSUE TITLE
[ERROR] (TypeError) "no implicit conversion of Symbol into Integer"

### ISSUE THREAD

**Issue by garethrees** [mysociety/foi-for-councils#425]
```
A TypeError occurred in background at 2021-03-24 12:29:37 UTC :

no implicit conversion of Symbol into Integer
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/icasework-0.1.0/lib/icasework/case.rb:39:in `case_details_data'

-------------------------------
Backtrace:
-------------------------------

/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/icasework-0.1.0/lib/icasework/case.rb:39:in `case_details_data'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/icasework-0.1.0/lib/icasework/case.rb:29:in `case_data'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/icasework-0.1.0/lib/icasework/case.rb:15:in `block in where'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/icasework-0.1.0/lib/icasework/case.rb:15:in `each'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/icasework-0.1.0/lib/icasework/case.rb:15:in `map'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/icasework-0.1.0/lib/icasework/case.rb:15:in `where'
/data/vhost/hackney-foi.staging.mysociety.org/foi-for-councils-2021-03-24T11-31-38/app/models/case_management/icasework.rb:39:in `published_requests'
/data/vhost/hackney-foi.staging.mysociety.org/foi-for-councils-2021-03-24T11-31-38/app/services/disclosure_log.rb:29:in `import'
/data/vhost/hackney-foi.staging.mysociety.org/foi-for-councils-2021-03-24T11-31-38/app/services/disclosure_log.rb:19:in `import!'
/data/vhost/hackney-foi.staging.mysociety.org/foi-for-councils-2021-03-24T11-31-38/app/workers/import_disclosure_log_worker.rb:11:in `perform'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:192:in `execute_job'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:165:in `block (2 levels) in process'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/sidekiq-5.2.9/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/sidekiq-5.2.9/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:164:in `block in process'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:137:in `block (6 levels) in dispatch'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/sidekiq-5.2.9/lib/sidekiq/job_retry.rb:109:in `local'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:136:in `block (5 levels) in dispatch'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/sidekiq-5.2.9/lib/sidekiq/rails.rb:43:in `block in call'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/activesupport-6.1.3/lib/active_support/execution_wrapper.rb:88:in `wrap'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/activesupport-6.1.3/lib/active_support/reloader.rb:72:in `block in wrap'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/activesupport-6.1.3/lib/active_support/execution_wrapper.rb:88:in `wrap'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/activesupport-6.1.3/lib/active_support/reloader.rb:71:in `wrap'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/sidekiq-5.2.9/lib/sidekiq/rails.rb:42:in `call'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:132:in `block (4 levels) in dispatch'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:250:in `stats'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:127:in `block (3 levels) in dispatch'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/sidekiq-5.2.9/lib/sidekiq/job_logger.rb:8:in `call'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:126:in `block (2 levels) in dispatch'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/sidekiq-5.2.9/lib/sidekiq/job_retry.rb:74:in `global'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:125:in `block in dispatch'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/sidekiq-5.2.9/lib/sidekiq/logging.rb:48:in `with_context'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/sidekiq-5.2.9/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:124:in `dispatch'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:163:in `process'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:83:in `process_one'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/sidekiq-5.2.9/lib/sidekiq/processor.rb:71:in `run'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/sidekiq-5.2.9/lib/sidekiq/util.rb:16:in `watchdog'
/data/vhost/hackney-foi.staging.mysociety.org/shared/vendor/bundle/gems/sidekiq-5.2.9/lib/sidekiq/util.rb:25:in `block in safe_thread'

-------------------------------
Data:
-------------------------------

* data: {:sidekiq=>
{:context=>"Job raised exception",
:job=>
{"class"=>"ImportDisclosureLogWorker",
"args"=>["week"],
"queue"=>"default",
"retry"=>true,
"jid"=>"b4c7b6072698143d02933a8b",
"created_at"=>1616547600.161598,
"enqueued_at"=>1616588976.5725336,
"error_message"=>"no implicit conversion of Symbol into Integer",
"error_class"=>"TypeError",
"failed_at"=>1616547600.5872934,
"retry_count"=>11,
"retried_at"=>1616574206.453047},
:jobstr=>
"{\"class\":\"ImportDisclosureLogWorker\",\"args\":[\"week\"],\"queue\":\"default\",\"retry\":true,\"jid\":\"b4c7b6072698143d02933a8b\",\"created_at\":1616547600.161598,\"enqueued_at\":1616588976.5725336,\"error_message\":\"no implicit conversion of Symbol into Integer\",\"error_class\":\"TypeError\",\"failed_at\":1616547600.5872934,\"retry_count\":11,\"retried_at\":1616574206.453047}"}}
```

**Comment by gbp** [comment]
Confirmed https://github.com/mysociety/icasework-ruby/commit/5290c76979b538f574cd655319759b5489d47207 fixed this. Sidekiq job has now completed.
